/**
 * Africa Edition — routes that must not render legacy content.
 * Maps old paths to Africa Edition entry points (see AFRICA_CONTENT_CLEANUP.md).
 */
export const AFRICA_ROUTE_REDIRECTS: Record<string, string> = {
  '/africa': '/',
  '/pricing': '/',
  '/features': '/',
  '/how-it-works': '/',
  '/persona-selection': '/africa/countries',
  '/personas': '/africa/countries',
  '/personas/cautious-parent': '/africa/countries',
  '/personas/private-individual': '/africa/countries',
  '/personas/online-shopper': '/africa/countries',
  '/personas/social-influencer': '/africa/countries',
  '/personas/privacy-advocate': '/africa/countries',
  '/personas/concerned-employee': '/africa/countries',
  '/privacy-journey': '/africa/roadmap',
  '/30-day-roadmap': '/',
  '/privacy-action-center': '/africa/countries',
  '/privacy-focus': '/',
  '/parent': '/',
  '/parent/onboarding': '/',
  '/parent/dashboard': '/',
  '/parent/dashboard/action-plan': '/',
  '/cautions': '/',
  '/simple-dashboard': '/',
  '/toolkit': '/africa/scamshield',
  '/test-assessment': '/',
  '/help': '/contact',
  '/help/action-plan': '/contact',
  '/help/getting-started': '/contact',
  '/resources': '/africa/sources',
  '/resources/guides': '/africa/sources',
  '/resources/checklists': '/africa/sources',
  '/resources/tools': '/africa/sources',
  '/resources/tools/privacy-assessment': '/assessment',
  '/resources/tools/personal-data-inventory': '/assessment',
  '/resources/tools/password-strength': '/assessment',
  '/blog': '/',
  '/blog/privacy-importance': '/',
  '/blog/data-protection-laws-2024': '/',
  '/blog/privacy-tools-social-media': '/',
  '/blog/children-privacy-protection': '/',
  '/blog/hidden-cost-free-services': '/',
  '/blog/privacy-browsers-comparison': '/',
  '/blog/privacy-laws-2025': '/',
  '/blog/workplace-privacy': '/',
  '/dashboard': '/',
  '/dashboard/action-plan': '/',
  '/dashboard/history': '/',
  '/dashboard/exposure-check': '/',
  '/dashboard/rights-checkup': '/',
  '/dashboard/complete-assessment': '/',
  '/dashboard/profile': '/',
  '/dashboard/settings': '/',
  '/dashboard/notifications': '/',
  '/dashboard/help': '/',
  '/dashboard/preferences': '/',
  '/dashboard/security': '/',
  '/dashboard/privacy': '/',
  '/dashboard/billing': '/',
  '/dashboard/data-export': '/',
  '/dashboard/account-deletion': '/',
  '/privacy-laws/gdpr': '/privacy-laws',
  '/privacy-laws/global-privacy-act': '/privacy-laws',
  '/privacy-laws/us-privacy': '/privacy-laws',
  '/privacy-laws/enforcement': '/privacy-laws',
  '/legal': '/privacy-laws',
};

/** @deprecated Import AFRICA_ROUTE_REDIRECTS instead */
export const AFRICA_LEGACY_REDIRECTS = AFRICA_ROUTE_REDIRECTS;
