import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Extend jsPDF type to include autoTable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

// Personal Data Inventory Export
export interface PersonalDataItem {
  id: string;
  category: string;
  name: string;
  description: string;
  sensitivity: 'low' | 'medium' | 'high';
  storedBy: string[];
  purpose: string;
  retention: string;
  sharedWith: string[];
  lastUpdated: string;
}

export const exportPersonalDataInventoryToPDF = (items: PersonalDataItem[]): void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;

  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Personal Data Inventory Report', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 10;

  // Summary Statistics
  const totalItems = items.length;
  const highSensitivity = items.filter(i => i.sensitivity === 'high').length;
  const mediumSensitivity = items.filter(i => i.sensitivity === 'medium').length;
  const lowSensitivity = items.filter(i => i.sensitivity === 'low').length;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 20, yPosition);
  yPosition += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Items: ${totalItems}`, 20, yPosition);
  yPosition += 6;
  doc.text(`High Sensitivity: ${highSensitivity}`, 20, yPosition);
  yPosition += 6;
  doc.text(`Medium Sensitivity: ${mediumSensitivity}`, 20, yPosition);
  yPosition += 6;
  doc.text(`Low Sensitivity: ${lowSensitivity}`, 20, yPosition);
  yPosition += 15;

  // Data Items Table
  if (items.length > 0) {
    const tableData = items.map(item => [
      item.name,
      item.category.replace('_', ' ').toUpperCase(),
      item.sensitivity.toUpperCase(),
      item.storedBy.join(', '),
      item.purpose,
      item.retention,
      item.sharedWith.join(', ') || 'None'
    ]);

    doc.autoTable({
      startY: yPosition,
      head: [['Name', 'Category', 'Sensitivity', 'Stored By', 'Purpose', 'Retention', 'Shared With']],
      body: tableData,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [66, 139, 202] },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      margin: { left: 20, right: 20 },
      columnStyles: {
        0: { cellWidth: 30 },
        1: { cellWidth: 25 },
        2: { cellWidth: 20 },
        3: { cellWidth: 35 },
        4: { cellWidth: 30 },
        5: { cellWidth: 20 },
        6: { cellWidth: 30 }
      }
    });
  }

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - 20, pageHeight - 10, { align: 'right' });
    doc.text('Generated by Social Caution Privacy Platform', 20, pageHeight - 10);
  }

  doc.save(`personal-data-inventory-${new Date().toISOString().split('T')[0]}.pdf`);
};

export const exportPersonalDataInventoryToCSV = (items: PersonalDataItem[]): void => {
  let csvContent = 'Personal Data Inventory Report\n';
  csvContent += `Generated on: ${new Date().toLocaleDateString()}\n\n`;
  csvContent += 'Name,Category,Sensitivity,Stored By,Purpose,Retention,Shared With,Last Updated\n';

  items.forEach(item => {
    const name = `"${item.name.replace(/"/g, '""')}"`;
    const category = item.category.replace('_', ' ').toUpperCase();
    const storedBy = `"${item.storedBy.join('; ').replace(/"/g, '""')}"`;
    const purpose = `"${item.purpose.replace(/"/g, '""')}"`;
    const sharedWith = `"${(item.sharedWith.join('; ') || 'None').replace(/"/g, '""')}"`;
    csvContent += `${name},${category},${item.sensitivity.toUpperCase()},${storedBy},${purpose},${item.retention},${sharedWith},${item.lastUpdated}\n`;
  });

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', `personal-data-inventory-${new Date().toISOString().split('T')[0]}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const exportPersonalDataInventoryToJSON = (items: PersonalDataItem[]): void => {
  const jsonData = {
    exportDate: new Date().toISOString(),
    version: '1.0',
    items: items
  };

  const blob = new Blob([JSON.stringify(jsonData, null, 2)], { type: 'application/json' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', `personal-data-inventory-${new Date().toISOString().split('T')[0]}.json`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// Password Strength Checker Export
export interface PasswordCheckData {
  password: string; // masked
  strength: 'weak' | 'fair' | 'good' | 'strong';
  score: number;
  checkedAt: string;
  requirements: {
    length: boolean;
    lowercase: boolean;
    uppercase: boolean;
    numbers: boolean;
    special: boolean;
  };
  estimatedCrackTime: string;
  feedback: string[];
}

export const exportPasswordCheckToPDF = (checkData: PasswordCheckData): void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;

  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Password Strength Report', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Checked on: ${new Date(checkData.checkedAt).toLocaleString()}`, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Strength Assessment
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Strength Assessment', 20, yPosition);
  yPosition += 10;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Password: ${checkData.password}`, 20, yPosition);
  yPosition += 8;

  doc.setFont('helvetica', 'bold');
  doc.text(`Strength: ${checkData.strength.toUpperCase()}`, 20, yPosition);
  yPosition += 8;

  doc.setFont('helvetica', 'normal');
  doc.text(`Score: ${checkData.score}/100`, 20, yPosition);
  yPosition += 8;

  doc.text(`Estimated Time to Crack: ${checkData.estimatedCrackTime}`, 20, yPosition);
  yPosition += 15;

  // Requirements Checklist
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Requirements Checklist', 20, yPosition);
  yPosition += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const requirements = [
    { label: 'At least 8 characters', met: checkData.requirements.length },
    { label: 'Contains lowercase letters', met: checkData.requirements.lowercase },
    { label: 'Contains uppercase letters', met: checkData.requirements.uppercase },
    { label: 'Contains numbers', met: checkData.requirements.numbers },
    { label: 'Contains special characters', met: checkData.requirements.special }
  ];

  requirements.forEach(req => {
    doc.text(`${req.met ? '✓' : '✗'} ${req.label}`, 25, yPosition);
    yPosition += 6;
  });

  yPosition += 10;

  // Recommendations
  if (checkData.feedback && checkData.feedback.length > 0) {
    if (yPosition > pageHeight - 60) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Recommendations', 20, yPosition);
    yPosition += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    checkData.feedback.forEach((item, index) => {
      if (yPosition > pageHeight - 30) {
        doc.addPage();
        yPosition = 20;
      }
      doc.text(`${index + 1}. ${item}`, 25, yPosition);
      yPosition += 6;
    });
  }

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - 20, pageHeight - 10, { align: 'right' });
    doc.text('Generated by Social Caution Privacy Platform', 20, pageHeight - 10);
  }

  doc.save(`password-check-${new Date().toISOString().split('T')[0]}.pdf`);
};

